import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c7c6c6",
        "primary-container": "#1c1b1b",
        secondary: "#5e5e5e",
        "on-error-container": "#93000a",
        "secondary-container": "#e1dfdf",
        "on-surface-variant": "#444748",
        "on-primary-fixed-variant": "#474646",
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        outline: "#747878",
        "primary-fixed-dim": "#c8c6c5",
        tertiary: "#000000",
        "inverse-primary": "#c8c6c5",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-fixed": "#0f0069",
        "primary-fixed": "#e5e2e1",
        background: "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1c",
        "surface-tint": "#5f5e5e",
        "on-primary-container": "#858383",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f1f1f1",
        "outline-variant": "#c4c7c7",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e2dfff",
        "on-tertiary-container": "#7671ff",
        "on-tertiary-fixed-variant": "#3323cc",
        primary: "#000000",
        "inverse-surface": "#2f3131",
        "on-primary": "#ffffff",
        "tertiary-container": "#0f0069",
        "surface-container-low": "#f4f3f3",
        "on-secondary-container": "#626262",
        "secondary-fixed": "#e4e2e2",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#1c1b1b",
        "surface-container": "#eeeeee",
        "on-secondary-fixed-variant": "#464747",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        accent: "#4F46E5",
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "row-padding": "12px",
        gutter: "16px",
        unit: "4px",
        "container-max": "800px",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
        "body-sm": ["Inter", "sans-serif"],
        "mono-data": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
